spring.application.name=Ar-Tech

spring.datasource.url = ${URL_DB}
spring.datasource.username = ${USER_DB}
spring.datasource.password = ${PASSWORD_DB}
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql = true

jwt.secret.key = ${JWT_SECRET_KEY}
jwt.expiration.time = ${JWT_EXPIRATION_TIME}

java.mail.sender = ${MAIL_SENDER}
java.mail.password = ${MAIL_PASSWORD}